server:
  port: 8100
  
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER_HOST:localhost}:${KAFKA_BROKER_PORT:9092}
      bindings:
        insurance-event-out:
          destination: InsuranceEventTopic
          content-type: application/json
#    kafka:
#      bootstrap-servers: ${KAFKA_BROKER_HOST:localhost}:${KAFKA_BROKER_PORT:9092}
  datasource:
    url: jdbc:mysql://localhost:3306/insurance_db?autoReconnect=true&useSSL=false
    username: pjaiswal
    password: 10PJ1980au#
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 20000 
      max-active: 50
      max-idle: 20
      min-idle: 15
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  
        format_sql: true 
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true
      
logging:
  level:
    org.springframework.web: WARN
    com.usl.microservices: DEBUG    